### ISSUE TITLE
"TypeError: oneai.Conversation is not a constructor"

### ISSUE THREAD

**Issue by lcamus** [oneai-nlp/oneai-node#11]
Hi,

I just tried your sample in node.js to transcribe audio (https://docs.oneai.com/docs/transcribe-audio).
I got the following error:

> const conversation = new oneai.Conversation(
                     ^
TypeError: oneai.Conversation is not a constructor
    at Object.<anonymous> (/home/laurent/dev/edu/oneai/hello.js:7:22)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

I installed your [last npm published](https://www.npmjs.com/package/oneai) and I use node js v19.3.0.

Thanks for your help.

**Comment by michgur** [comment]
Thanks for reporting this!

That code is outdated, should be

```
const { OneAI } = require("oneai"); const oneai = new
OneAI("<YOUR-API-KEY-HERE>"); const pipeline = new oneai.Pipeline(
oneai.skills.transcribe({ speaker_detection: true, }) );
pipeline.runFile("YOUR_FILE_PATH").then(console.log);
```

We'll fix the code in the docs asap.

Thanks again!
// michael

**Comment by michgur** [comment]
Bad snippet in docs

**Comment by dagolinuxoid** [comment]
@michgur hi there. The code
```javascript
const { OneAI } = require("oneai");

const oneai = new OneAI("<MY-WORKING-IN-STUDIO_IPA_HERE");
const pipeline = new oneai.Pipeline(
  oneai.skills.transcribe({
    speaker_detection: true
  })
);

pipeline.runFile("roth.mp3").then(console.log);
```
unfortunately produces the following result
```bash
📁 ~/Public/one_ai
🌸 node script.js
●▲▮ Upload of file roth.mp3 complete
●▲▮ Processing file roth.mp3 - status RUNNING - 0s 209ms/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/mapping.js:137
    console.log(error.response.data);
                               ^

TypeError: Cannot read properties of undefined (reading 'data')
    at buildError (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/mapping.js:137:32)
    at buildAsyncApiResponse (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/mapping.js:153:18)
    at PipelineApiClient.<anonymous> (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/pipeline.js:103:83)
    at step (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/pipeline.js:33:23)
    at Object.next (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/pipeline.js:14:53)
    at fulfilled (/home/ah/Public/one_ai/node_modules/oneai/lib/src/api/pipeline.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0
```
Any idea how to fix it? ( Website one ai studio version works though )
